/**
 * OfficerPage Component - Complete UI Overhaul
 * Beautiful village officer agent interface with world-class design
 */

import { useState } from 'react';
import { Link } from 'react-router-dom';
import RiskBadge from '../components/RiskBadge';
import AlertBanner from '../components/AlertBanner';
import AgentThinking from '../components/AgentThinking';
import ExplainabilityPanel from '../components/ExplainabilityPanel';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Table, TableRow, TableCell, WidthType, ShadingType, Header, Footer, PageNumber } from "docx";
import { saveAs } from "file-saver";

const STATES_DISTRICTS = {
  Punjab: ["Ludhiana", "Amritsar", "Patiala", "Bathinda"],
  Rajasthan: ["Jaipur", "Jodhpur", "Bikaner", "Barmer"],
  "Tamil Nadu": ["Madurai", "Chennai", "Coimbatore", "Trichy"],
  "Andhra Pradesh": ["Guntur", "Kurnool", "Anantapur", "Nellore"],
  Maharashtra: ["Latur", "Aurangabad", "Nashik", "Pune"],
  "Uttar Pradesh": ["Agra", "Varanasi", "Meerut", "Allahabad"],
};

export default function OfficerPage() {
  const [state, setState] = useState("");
  const [district, setDistrict] = useState("");
  const [responseData, setResponseData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResponseData(null);

    try {
      const API_URL = import.meta.env.VITE_API_URL || 'https://yld21dvaua.execute-api.us-east-1.amazonaws.com/advice';
      const res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ role: 'officer', state, district }),
      });

      if (!res.ok) throw new Error('API request failed');

      const data = await res.json();
      const parsed = data.body ? JSON.parse(data.body) : data;
      
      if (parsed.error) throw new Error(parsed.error);
      
      setResponseData(parsed);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = async () => {
    if (!responseData) return;
    const d = responseData;
    const r = responseData.response;

    const clean = (val) => {
      if (val === null || val === undefined) return "N/A";
      if (typeof val === "object") return JSON.stringify(val);
      return String(val).replace(/₹/g, "Rs.").trim();
    };

    const doc = new Document({
      styles: {
        default: { 
          document: { 
            run: { font: "Calibri", size: 22 } 
          } 
        }
      },
      sections: [{
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "WISE DROP  |  Village Officer SDG 6 Compliance Report  |  AWS AI for Bharat 2026", size: 16, color: "1e40af" })
                ],
                border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "1e40af" } }
              })
            ]
          })
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "Generated by Wise Drop  |  Powered by Amazon Bedrock Nova Pro  |  SDG 6 Aligned  |  Page ", size: 16, color: "64748b" }), 
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "64748b" })
                ],
                alignment: AlignmentType.CENTER
              })
            ]
          })
        },
        children: [
          new Paragraph({ 
            children: [new TextRun({ text: "WISE DROP", bold: true, size: 52, color: "1e40af" })], 
            alignment: AlignmentType.CENTER, 
            spacing: { before: 400, after: 100 } 
          }),
          new Paragraph({ 
            children: [new TextRun({ text: "SDG 6 Compliance Report", size: 30, color: "0891b2", italics: true })], 
            alignment: AlignmentType.CENTER, 
            spacing: { after: 400 } 
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "District", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" }, width: { size: 30, type: WidthType.PERCENTAGE } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: clean(d.district) })] })] }),
                ]
              }),
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "State", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: clean(d.state) })] })] }),
                ]
              }),
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Risk Level", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${clean(d.risk?.risk_category)} (Score: ${d.risk?.risk_score ?? "N/A"}/100)`, bold: true })] })] }),
                ]
              }),
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Generated", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: new Date().toLocaleString("en-IN") })] })] }),
                ]
              }),
            ]
          }),
          new Paragraph({ spacing: { after: 300 } }),
          new Paragraph({ 
            children: [new TextRun({ text: "EXECUTIVE SUMMARY", bold: true, size: 28, color: "1e40af" })], 
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } }, 
            spacing: { before: 300, after: 200 } 
          }),
          new Paragraph({ 
            children: [new TextRun({ text: clean(r?.executive_summary), italics: true, color: "334155" })], 
            spacing: { after: 300 } 
          }),
          new Paragraph({ 
            children: [new TextRun({ text: "KEY FINDINGS", bold: true, size: 28, color: "1e40af" })], 
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } }, 
            spacing: { before: 300, after: 200 } 
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({ 
                tableHeader: true, 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Finding", bold: true, color: "ffffff" })] })], shading: { type: ShadingType.CLEAR, fill: "1e40af" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Status", bold: true, color: "ffffff" })] })], shading: { type: ShadingType.CLEAR, fill: "1e40af" } }),
                ]
              }),
              ...[
                ["Aquifer Status", clean(r?.key_findings?.aquifer_status)],
                ["Contamination Risk", clean(r?.key_findings?.contamination_risk)],
                ["Extraction vs Recharge", clean(r?.key_findings?.extraction_vs_recharge)],
                ["SDG 6 Compliance", clean(r?.key_findings?.sdg6_compliance)],
              ].map(([label, value], i) =>
                new TableRow({ 
                  children: [
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })], shading: { type: ShadingType.CLEAR, fill: i % 2 === 0 ? "f8fafc" : "ffffff" } }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: value })] })], shading: { type: ShadingType.CLEAR, fill: i % 2 === 0 ? "f8fafc" : "ffffff" } }),
                  ]
                })
              )
            ]
          }),
          new Paragraph({ spacing: { after: 200 } }),
          new Paragraph({ 
            children: [new TextRun({ text: "RECOMMENDATIONS", bold: true, size: 28, color: "1e40af" })], 
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } }, 
            spacing: { before: 300, after: 200 } 
          }),
          new Paragraph({ 
            children: [new TextRun({ text: "Immediate Actions:", bold: true, color: "dc2626" })], 
            spacing: { after: 100 } 
          }),
          ...(r?.recommendations?.immediate_actions || ["N/A"]).map((item, i) =>
            new Paragraph({ 
              children: [
                new TextRun({ text: `${i + 1}.  `, bold: true, color: "dc2626" }), 
                new TextRun({ text: clean(item) })
              ], 
              spacing: { after: 100 }, 
              indent: { left: 360 } 
            })
          ),
          new Paragraph({ 
            children: [new TextRun({ text: "Farmer Support:", bold: true, color: "0891b2" })], 
            spacing: { before: 200, after: 100 } 
          }),
          ...(r?.recommendations?.farmer_support || ["N/A"]).map((item, i) =>
            new Paragraph({ 
              children: [
                new TextRun({ text: `${i + 1}.  `, bold: true, color: "0891b2" }), 
                new TextRun({ text: clean(item) })
              ], 
              spacing: { after: 100 }, 
              indent: { left: 360 } 
            })
          ),
          new Paragraph({ spacing: { after: 200 } }),
          new Paragraph({ 
            children: [new TextRun({ text: "AI-GENERATED INSIGHTS", bold: true, size: 28, color: "1e40af" })], 
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } }, 
            spacing: { before: 300, after: 200 } 
          }),
          new Paragraph({ 
            children: [new TextRun({ text: clean(r?.ai_generated_insights), italics: true, color: "1e40af", bold: true })], 
            spacing: { after: 300 } 
          }),
        ]
      }]
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `WiseDrop_Officer_${clean(d.district)}_${new Date().toISOString().split("T")[0]}.docx`);
  };

  const reset = () => {
    setState("");
    setDistrict("");
    setResponseData(null);
    setError(null);
  };

  const getSDGStatus = (finding, keyword) => {
    if (!finding) return false;
    return finding.toLowerCase().includes(keyword.toLowerCase());
  };

  return (
    <div className="min-h-screen bg-blue-50">
      {/* Page Header */}
      <div className="bg-gradient-to-r from-blue-800 to-cyan-600 py-12 px-6 text-white">
        <div className="max-w-5xl mx-auto">
          <Link to="/" className="text-cyan-200 text-sm hover:text-cyan-100 mb-3 inline-block">
            ← Wise Drop
          </Link>
          <h1 className="text-4xl font-black mb-2">🏛️ Village Officer Agent</h1>
          <p className="text-cyan-100 text-base">
            SDG 6 compliance reports & contamination monitoring
          </p>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Input Form */}
        {!responseData && !loading && (
          <div className="bg-white rounded-2xl shadow-xl p-8 -mt-6 relative z-10">
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* State Select */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">
                  State
                </label>
                <div className="relative">
                  <select
                    value={state}
                    onChange={(e) => { setState(e.target.value); setDistrict(""); }}
                    required
                    className="w-full border-2 border-slate-200 rounded-xl px-4 py-3 text-slate-800 focus:border-blue-500 focus:outline-none bg-white appearance-none cursor-pointer text-base"
                  >
                    <option value="">-- Select State --</option>
                    {Object.keys(STATES_DISTRICTS).map((s) => (
                      <option key={s} value={s}>{s}</option>
                    ))}
                  </select>
                  <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400 pointer-events-none">
                    ▼
                  </div>
                </div>
              </div>

              {/* District Select */}
              <div>
                <label className="text-sm font-semibold text-slate-700 mb-2 block">
                  District
                </label>
                <div className="relative">
                  <select
                    value={district}
                    onChange={(e) => setDistrict(e.target.value)}
                    disabled={!state}
                    required
                    className="w-full border-2 border-slate-200 rounded-xl px-4 py-3 text-slate-800 focus:border-blue-500 focus:outline-none bg-white appearance-none cursor-pointer text-base disabled:bg-slate-50 disabled:cursor-not-allowed"
                  >
                    <option value="">-- Select District --</option>
                    {(STATES_DISTRICTS[state] || []).map((d) => (
                      <option key={d} value={d}>{d}</option>
                    ))}
                  </select>
                  <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400 pointer-events-none">
                    ▼
                  </div>
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={!state || !district}
                className="w-full bg-gradient-to-r from-blue-700 to-cyan-600 text-white font-bold py-4 rounded-xl text-base hover:from-blue-800 hover:to-cyan-700 transition-all duration-200 shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
              >
                📊 Generate Officer Report
              </button>
            </form>
          </div>
        )}

        {/* Loading State */}
        {loading && (
          <div className="-mt-6 relative z-10">
            <AgentThinking role="officer" />
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="bg-red-50 border-2 border-red-200 rounded-2xl p-6 -mt-6 relative z-10">
            <p className="text-red-800 font-semibold mb-2">❌ Error</p>
            <p className="text-red-600 mb-4">{error}</p>
            <button
              onClick={reset}
              className="text-red-600 hover:text-red-800 font-medium text-sm"
            >
              ← Try Again
            </button>
          </div>
        )}

        {/* Results */}
        {responseData && (
          <div className="space-y-6 -mt-6 relative z-10">
            {/* Results Header Card */}
            <div className="bg-white rounded-2xl shadow-xl p-6">
              <div className="flex flex-wrap justify-between items-start gap-4 mb-4">
                <div>
                  <h2 className="text-2xl font-bold text-slate-900 mb-1">
                    {responseData.response?.report_title || `Officer Report`}
                  </h2>
                  <p className="text-sm text-slate-500">
                    📍 {responseData.district}, {responseData.state}
                  </p>
                  <p className="text-xs text-slate-400 mt-1">
                    Generated: {new Date(responseData.generated_at).toLocaleString()}
                  </p>
                </div>
                <div className="flex gap-3 items-center">
                  {responseData.risk && (
                    <RiskBadge
                      risk_score={responseData.risk.risk_score}
                      risk_category={responseData.risk.risk_category}
                    />
                  )}
                  <button
                    onClick={downloadReport}
                    className="bg-slate-100 hover:bg-slate-200 border border-slate-300 rounded-xl px-4 py-2 text-sm font-semibold text-slate-700 transition-colors"
                  >
                    📥 Download Report (.docx)
                  </button>
                </div>
              </div>

              {/* Alert Banner */}
              {responseData.alerts && responseData.alerts.length > 0 && (
                <AlertBanner alerts={responseData.alerts} />
              )}
            </div>

            {/* Executive Summary */}
            {responseData.response?.executive_summary && (
              <div className="bg-white rounded-2xl shadow-md p-6 border-l-4 border-blue-500">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">
                  📋 Executive Summary
                </h3>
                <p className="text-slate-800 text-base leading-relaxed">
                  {responseData.response.executive_summary}
                </p>
              </div>
            )}

            {/* Key Findings Grid */}
            {responseData.response?.key_findings && (
              <div className="bg-white rounded-2xl shadow-md p-6">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">
                  🔍 Key Findings
                </h3>
                <div className="space-y-4">
                  {responseData.response.key_findings.aquifer_status && (
                    <div className="bg-blue-50 rounded-xl p-4 border border-blue-100">
                      <h4 className="font-semibold text-blue-900 mb-2 text-sm">💧 Aquifer Status</h4>
                      <p className="text-slate-700 text-sm leading-relaxed">
                        {responseData.response.key_findings.aquifer_status}
                      </p>
                    </div>
                  )}
                  {responseData.response.key_findings.contamination_risk && (
                    <div className="bg-red-50 rounded-xl p-4 border border-red-100">
                      <h4 className="font-semibold text-red-900 mb-2 text-sm">⚠️ Contamination Risk</h4>
                      <p className="text-slate-700 text-sm leading-relaxed">
                        {responseData.response.key_findings.contamination_risk}
                      </p>
                    </div>
                  )}
                  {responseData.response.key_findings.extraction_vs_recharge && (
                    <div className="bg-green-50 rounded-xl p-4 border border-green-100">
                      <h4 className="font-semibold text-green-900 mb-2 text-sm">⚖️ Extraction vs Recharge</h4>
                      <p className="text-slate-700 text-sm leading-relaxed">
                        {responseData.response.key_findings.extraction_vs_recharge}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* SDG 6 Compliance Tracker */}
            <div className="bg-gradient-to-br from-blue-50 to-cyan-50 rounded-2xl shadow-md p-6 border border-blue-200">
              <h3 className="text-sm font-bold text-blue-900 uppercase tracking-wider mb-4">
                🌐 SDG 6 Compliance Tracker
              </h3>
              <div className="space-y-3">
                <div className="flex justify-between items-center bg-white rounded-xl p-4">
                  <span className="text-slate-700 font-semibold text-sm">SDG 6.3 — Water Quality</span>
                  <span className={`px-4 py-1.5 rounded-full text-xs font-bold ${
                    getSDGStatus(responseData.response?.key_findings?.contamination_risk, 'none') || 
                    getSDGStatus(responseData.response?.key_findings?.contamination_risk, 'low')
                      ? 'bg-green-500 text-white'
                      : 'bg-red-500 text-white'
                  }`}>
                    {getSDGStatus(responseData.response?.key_findings?.contamination_risk, 'none') || 
                     getSDGStatus(responseData.response?.key_findings?.contamination_risk, 'low')
                      ? '✅ On Track'
                      : '⚠️ At Risk'}
                  </span>
                </div>
                <div className="flex justify-between items-center bg-white rounded-xl p-4">
                  <span className="text-slate-700 font-semibold text-sm">SDG 6.4 — Water Efficiency</span>
                  <span className={`px-4 py-1.5 rounded-full text-xs font-bold ${
                    getSDGStatus(responseData.response?.key_findings?.extraction_vs_recharge, 'sustainable')
                      ? 'bg-green-500 text-white'
                      : 'bg-red-500 text-white'
                  }`}>
                    {getSDGStatus(responseData.response?.key_findings?.extraction_vs_recharge, 'sustainable')
                      ? '✅ On Track'
                      : '⚠️ At Risk'}
                  </span>
                </div>
                <div className="flex justify-between items-center bg-white rounded-xl p-4">
                  <span className="text-slate-700 font-semibold text-sm">SDG 6.5 — Water Management</span>
                  <span className={`px-4 py-1.5 rounded-full text-xs font-bold ${
                    responseData.response?.key_findings?.sdg6_compliance === 'On Track'
                      ? 'bg-green-500 text-white'
                      : 'bg-red-500 text-white'
                  }`}>
                    {responseData.response?.key_findings?.sdg6_compliance === 'On Track'
                      ? '✅ On Track'
                      : '⚠️ At Risk'}
                  </span>
                </div>
              </div>
            </div>

            {/* Recommendations */}
            {responseData.response?.recommendations && (
              <div className="bg-white rounded-2xl shadow-md p-6">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">
                  💡 Recommendations
                </h3>
                <div className="space-y-5">
                  {responseData.response.recommendations.immediate_actions && (
                    <div>
                      <h4 className="font-bold text-slate-800 mb-2 text-sm">🚨 Immediate Actions</h4>
                      <ul className="space-y-2">
                        {responseData.response.recommendations.immediate_actions.map((action, i) => (
                          <li key={i} className="flex items-start gap-2 text-slate-700 text-sm">
                            <span className="text-blue-500 mt-0.5">▸</span>
                            <span>{action}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {responseData.response.recommendations.policy_proposals && (
                    <div>
                      <h4 className="font-bold text-slate-800 mb-2 text-sm">📜 Policy Proposals</h4>
                      <ul className="space-y-2">
                        {responseData.response.recommendations.policy_proposals.map((policy, i) => (
                          <li key={i} className="flex items-start gap-2 text-slate-700 text-sm">
                            <span className="text-cyan-500 mt-0.5">▸</span>
                            <span>{policy}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {responseData.response.recommendations.farmer_support && (
                    <div>
                      <h4 className="font-bold text-slate-800 mb-2 text-sm">🧑‍🌾 Farmer Support</h4>
                      <ul className="space-y-2">
                        {responseData.response.recommendations.farmer_support.map((support, i) => (
                          <li key={i} className="flex items-start gap-2 text-slate-700 text-sm">
                            <span className="text-green-500 mt-0.5">▸</span>
                            <span>{support}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* AI Insights */}
            {responseData.response?.ai_generated_insights && (
              <div className="bg-gradient-to-r from-blue-600 to-cyan-600 rounded-2xl shadow-md p-6 text-white">
                <h3 className="text-sm font-bold uppercase tracking-wider mb-3">
                  🤖 AI Generated Insights
                </h3>
                <p className="text-cyan-50 text-base leading-relaxed">
                  {responseData.response.ai_generated_insights}
                </p>
              </div>
            )}

            {/* Explainability Panel */}
            <ExplainabilityPanel
              calculations={responseData.response?.key_findings}
              reasoning={responseData.response?.executive_summary}
              sources={responseData.response?.methodology?.data_sources}
              tools={responseData.response?.methodology?.ai_tools}
            />

            {/* Reset Button */}
            <button
              onClick={reset}
              className="w-full bg-white hover:bg-slate-50 border-2 border-slate-200 rounded-xl px-4 py-3 font-semibold text-slate-700 transition-colors"
            >
              🔄 New Query
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
