/**
 * PolicymakerPage Component - Complete UI Overhaul
 * Beautiful policy maker agent interface with simulation sliders
 */

import { useState } from 'react';
import { Link } from 'react-router-dom';
import RiskBadge from '../components/RiskBadge';
import AlertBanner from '../components/AlertBanner';
import AgentThinking from '../components/AgentThinking';
import ExplainabilityPanel from '../components/ExplainabilityPanel';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Table, TableRow, TableCell, WidthType, ShadingType, Header, Footer, PageNumber } from "docx";
import { saveAs } from "file-saver";

const STATES_DISTRICTS = {
  Punjab: ["Ludhiana", "Amritsar", "Patiala", "Bathinda"],
  Rajasthan: ["Jaipur", "Jodhpur", "Bikaner", "Barmer"],
  "Tamil Nadu": ["Madurai", "Chennai", "Coimbatore", "Trichy"],
  "Andhra Pradesh": ["Guntur", "Kurnool", "Anantapur", "Nellore"],
  Maharashtra: ["Latur", "Aurangabad", "Nashik", "Pune"],
  "Uttar Pradesh": ["Agra", "Varanasi", "Meerut", "Allahabad"],
};

export default function PolicymakerPage() {
  const [state, setState] = useState("");
  const [district, setDistrict] = useState("");
  const [subsidyCrore, setSubsidyCrore] = useState(500);
  const [targetBlocks, setTargetBlocks] = useState(50);
  const [responseData, setResponseData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async () => {
    if (!state || !district) return;
    
    setLoading(true);
    setError(null);
    setResponseData(null);

    try {
      const API_URL = import.meta.env.VITE_API_URL || 'https://yld21dvaua.execute-api.us-east-1.amazonaws.com/advice';
      const res = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          role: 'policymaker', 
          state, 
          district,
          subsidy_crore: subsidyCrore,
          target_blocks: targetBlocks
        }),
      });

      if (!res.ok) throw new Error('API request failed');

      const data = await res.json();
      const parsed = data.body ? JSON.parse(data.body) : data;
      
      if (parsed.error) throw new Error(parsed.error);
      
      setResponseData(parsed);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = async () => {
    if (!responseData) return;
    const d = responseData;
    const r = responseData.response;

    const clean = (val) => {
      if (val === null || val === undefined) return "N/A";
      if (typeof val === "object") {
        if (val.intervention) return String(val.intervention).replace(/₹/g, "Rs.").trim();
        return JSON.stringify(val);
      }
      return String(val).replace(/₹/g, "Rs.").trim();
    };

    const doc = new Document({
      styles: {
        default: {
          document: {
            run: { font: "Calibri", size: 22 }
          }
        }
      },
      sections: [{
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "WISE DROP  |  AI-Powered Groundwater Intelligence  |  AWS AI for Bharat 2026", size: 16, color: "1e40af", font: "Calibri" }),
                ],
                border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "1e40af" } }
              })
            ]
          })
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "Generated by Wise Drop  |  Powered by Amazon Bedrock Nova Pro  |  SDG 6 Aligned  |  Page ", size: 16, color: "64748b" }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "64748b" }),
                ],
                alignment: AlignmentType.CENTER,
                border: { top: { style: BorderStyle.SINGLE, size: 4, color: "e2e8f0" } }
              })
            ]
          })
        },
        children: [
          // Cover Block
          new Paragraph({
            children: [new TextRun({ text: "WISE DROP", bold: true, size: 52, color: "1e40af", font: "Calibri" })],
            alignment: AlignmentType.CENTER,
            spacing: { before: 400, after: 100 }
          }),
          new Paragraph({
            children: [new TextRun({ text: "AI-Powered Groundwater Intelligence for India", size: 26, color: "0891b2", italics: true })],
            alignment: AlignmentType.CENTER,
            spacing: { after: 80 }
          }),
          new Paragraph({
            children: [new TextRun({ text: "POLICY MAKER SIMULATION REPORT", bold: true, size: 24, color: "64748b" })],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 }
          }),
          // Meta Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "District", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" }, width: { size: 30, type: WidthType.PERCENTAGE } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: clean(d.district) })] })], width: { size: 70, type: WidthType.PERCENTAGE } }),
                ]
              }),
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "State", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: clean(d.state) })] })] }),
                ]
              }),
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Generated", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: new Date().toLocaleString("en-IN") })] })] }),
                ]
              }),
              new TableRow({ 
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Risk Level", bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: `${clean(d.risk?.risk_category)} (Score: ${d.risk?.risk_score ?? "N/A"}/100)`, bold: true, color: d.risk?.risk_category === "Critical" ? "dc2626" : d.risk?.risk_category === "High Risk" ? "ea580c" : "16a34a" })] })] }),
                ]
              }),
            ]
          }),
          new Paragraph({ spacing: { after: 300 } }),
          // Key Statistics
          new Paragraph({
            children: [new TextRun({ text: "KEY STATISTICS", bold: true, size: 28, color: "1e40af" })],
            heading: HeadingLevel.HEADING_2,
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } },
            spacing: { before: 300, after: 200 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                tableHeader: true,
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Metric", bold: true, color: "ffffff" })] })], shading: { type: ShadingType.CLEAR, fill: "1e40af" } }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Value", bold: true, color: "ffffff" })] })], shading: { type: ShadingType.CLEAR, fill: "1e40af" } }),
                ]
              }),
              ...[
                ["Water Stress Index", clean(r?.key_stats?.water_stress_index)],
                ["Estimated Depletion Rate", clean(r?.key_stats?.estimated_depletion_rate)],
                ["Contamination Zone Risk", clean(r?.key_stats?.contamination_zone_risk)],
                ["SDG 6 Gap", clean(r?.key_stats?.sdg6_gap)],
              ].map(([label, value], i) =>
                new TableRow({ 
                  children: [
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })], shading: { type: ShadingType.CLEAR, fill: i % 2 === 0 ? "f8fafc" : "ffffff" } }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: value })] })], shading: { type: ShadingType.CLEAR, fill: i % 2 === 0 ? "f8fafc" : "ffffff" } }),
                  ]
                })
              )
            ]
          }),
          new Paragraph({ spacing: { after: 300 } }),
          // Immediate Recommendations
          new Paragraph({
            children: [new TextRun({ text: "IMMEDIATE POLICY ACTIONS", bold: true, size: 28, color: "1e40af" })],
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } },
            spacing: { before: 300, after: 200 }
          }),
          ...(r?.recommendations?.immediate || ["N/A"]).map((item, i) =>
            new Paragraph({
              children: [
                new TextRun({ text: `${i + 1}.  `, bold: true, color: "1e40af" }),
                new TextRun({ text: clean(item) }),
              ],
              spacing: { after: 120 },
              indent: { left: 360 }
            })
          ),
          new Paragraph({ spacing: { after: 200 } }),
          // Long Term Strategy
          new Paragraph({
            children: [new TextRun({ text: "LONG TERM STRATEGY", bold: true, size: 28, color: "1e40af" })],
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } },
            spacing: { before: 300, after: 200 }
          }),
          ...(r?.recommendations?.long_term || ["N/A"]).map((item, i) =>
            new Paragraph({
              children: [
                new TextRun({ text: `${i + 1}.  `, bold: true, color: "0891b2" }),
                new TextRun({ text: clean(item) }),
              ],
              spacing: { after: 120 },
              indent: { left: 360 }
            })
          ),
          new Paragraph({ spacing: { after: 200 } }),
          // Risk Mitigation
          new Paragraph({
            children: [new TextRun({ text: "RISK MITIGATION", bold: true, size: 28, color: "1e40af" })],
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } },
            spacing: { before: 300, after: 200 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              ...[
                ["Small Farmers", clean(r?.risk_mitigation?.small_farmers)],
                ["Supply Chain", clean(r?.risk_mitigation?.supply_chain)],
                ["Monitoring", clean(r?.risk_mitigation?.monitoring_framework)],
              ].map(([label, value], i) =>
                new TableRow({ 
                  children: [
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" }, width: { size: 25, type: WidthType.PERCENTAGE } }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: value })] })] }),
                  ]
                })
              )
            ]
          }),
          new Paragraph({ spacing: { after: 300 } }),
          // AI Insights
          new Paragraph({
            children: [new TextRun({ text: "AI-GENERATED INSIGHTS", bold: true, size: 28, color: "1e40af" })],
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "bfdbfe" } },
            spacing: { before: 300, after: 200 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              ...[
                ["Aquifer Recovery", clean(r?.ai_insights?.aquifer_recovery_projection)],
                ["Economic Impact", clean(r?.ai_insights?.economic_impact)],
                ["SDG 6 Alignment", clean(r?.ai_insights?.sdg6_alignment)],
              ].map(([label, value]) =>
                new TableRow({ 
                  children: [
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, color: "1e40af" })] })], shading: { type: ShadingType.CLEAR, fill: "eff6ff" }, width: { size: 25, type: WidthType.PERCENTAGE } }),
                    new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: value, bold: true })] })] }),
                  ]
                })
              )
            ]
          }),
        ]
      }]
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `WiseDrop_Policy_${clean(d.district)}_${new Date().toISOString().split("T")[0]}.docx`);
  };

  const reset = () => {
    setState("");
    setDistrict("");
    setResponseData(null);
    setError(null);
    setSubsidyCrore(500);
    setTargetBlocks(50);
  };

  return (
    <div className="min-h-screen bg-purple-50">
      {/* Page Header */}
      <div className="bg-gradient-to-r from-purple-800 to-violet-600 py-12 px-6 text-white">
        <div className="max-w-5xl mx-auto">
          <Link to="/" className="text-purple-200 text-sm hover:text-purple-100 mb-3 inline-block">
            ← Wise Drop
          </Link>
          <h1 className="text-4xl font-black mb-2">📊 Policy Maker Agent</h1>
          <p className="text-purple-100 text-base">
            State-level simulations & economic impact projections
          </p>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Input Form and Simulation Sliders */}
        {!responseData && !loading && (
          <div className="space-y-6 -mt-6 relative z-10">
            {/* Location Selection Card */}
            <div className="bg-white rounded-2xl shadow-xl p-8">
              <h3 className="text-lg font-bold text-slate-800 mb-6">📍 Select Location</h3>
              <div className="space-y-6">
                {/* State Select */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">
                    State
                  </label>
                  <div className="relative">
                    <select
                      value={state}
                      onChange={(e) => { setState(e.target.value); setDistrict(""); }}
                      required
                      className="w-full border-2 border-slate-200 rounded-xl px-4 py-3 text-slate-800 focus:border-purple-500 focus:outline-none bg-white appearance-none cursor-pointer text-base"
                    >
                      <option value="">-- Select State --</option>
                      {Object.keys(STATES_DISTRICTS).map((s) => (
                        <option key={s} value={s}>{s}</option>
                      ))}
                    </select>
                    <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400 pointer-events-none">
                      ▼
                    </div>
                  </div>
                </div>

                {/* District Select */}
                <div>
                  <label className="text-sm font-semibold text-slate-700 mb-2 block">
                    District
                  </label>
                  <div className="relative">
                    <select
                      value={district}
                      onChange={(e) => setDistrict(e.target.value)}
                      disabled={!state}
                      required
                      className="w-full border-2 border-slate-200 rounded-xl px-4 py-3 text-slate-800 focus:border-purple-500 focus:outline-none bg-white appearance-none cursor-pointer text-base disabled:bg-slate-50 disabled:cursor-not-allowed"
                    >
                      <option value="">-- Select District --</option>
                      {(STATES_DISTRICTS[state] || []).map((d) => (
                        <option key={d} value={d}>{d}</option>
                      ))}
                    </select>
                    <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400 pointer-events-none">
                      ▼
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Policy Simulation Engine Card */}
            <div className="bg-gradient-to-br from-purple-100 to-violet-100 rounded-2xl shadow-xl p-8 border border-purple-200">
              <h3 className="text-lg font-bold text-purple-900 mb-6">🎛️ Policy Simulation Engine</h3>
              
              <div className="space-y-8">
                {/* Subsidy Budget Slider */}
                <div>
                  <div className="flex justify-between items-center mb-3">
                    <label className="text-sm font-semibold text-purple-900">
                      Subsidy Budget
                    </label>
                    <span className="text-2xl font-black text-purple-700">
                      ₹{subsidyCrore} Cr
                    </span>
                  </div>
                  <input
                    type="range"
                    min="100"
                    max="2000"
                    step="100"
                    value={subsidyCrore}
                    onChange={(e) => setSubsidyCrore(Number(e.target.value))}
                    className="w-full h-3 bg-white rounded-full appearance-none cursor-pointer accent-purple-600 shadow-inner"
                  />
                  <div className="flex justify-between text-xs text-purple-600 mt-2 font-medium">
                    <span>₹100 Cr</span>
                    <span>₹2000 Cr</span>
                  </div>
                </div>

                {/* Target Blocks Slider */}
                <div>
                  <div className="flex justify-between items-center mb-3">
                    <label className="text-sm font-semibold text-purple-900">
                      Target Blocks
                    </label>
                    <span className="text-2xl font-black text-purple-700">
                      {targetBlocks} Blocks
                    </span>
                  </div>
                  <input
                    type="range"
                    min="10"
                    max="200"
                    step="10"
                    value={targetBlocks}
                    onChange={(e) => setTargetBlocks(Number(e.target.value))}
                    className="w-full h-3 bg-white rounded-full appearance-none cursor-pointer accent-purple-600 shadow-inner"
                  />
                  <div className="flex justify-between text-xs text-purple-600 mt-2 font-medium">
                    <span>10 Blocks</span>
                    <span>200 Blocks</span>
                  </div>
                </div>

                {/* Run Simulation Button */}
                <button
                  onClick={handleSubmit}
                  disabled={!state || !district}
                  className="w-full bg-gradient-to-r from-purple-700 to-violet-600 text-white font-bold py-4 rounded-xl text-base hover:from-purple-800 hover:to-violet-700 transition-all duration-200 shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  🚀 Run AI Simulation
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Loading State */}
        {loading && (
          <div className="-mt-6 relative z-10">
            <AgentThinking role="policymaker" />
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="bg-red-50 border-2 border-red-200 rounded-2xl p-6 -mt-6 relative z-10">
            <p className="text-red-800 font-semibold mb-2">❌ Error</p>
            <p className="text-red-600 mb-4">{error}</p>
            <button
              onClick={reset}
              className="text-red-600 hover:text-red-800 font-medium text-sm"
            >
              ← Try Again
            </button>
          </div>
        )}

        {/* Results */}
        {responseData && (
          <div className="space-y-6 -mt-6 relative z-10">
            {/* Results Header Card */}
            <div className="bg-white rounded-2xl shadow-xl p-6">
              <div className="flex flex-wrap justify-between items-start gap-4 mb-4">
                <div>
                  <h2 className="text-2xl font-bold text-slate-900 mb-1">
                    {responseData.response?.title || `Policy Brief`}
                  </h2>
                  <p className="text-sm text-slate-500">
                    📍 {responseData.district}, {responseData.state}
                  </p>
                  <p className="text-xs text-slate-400 mt-1">
                    Generated: {new Date(responseData.generated_at).toLocaleString()}
                  </p>
                </div>
                <div className="flex gap-3 items-center">
                  {responseData.risk && (
                    <RiskBadge
                      risk_score={responseData.risk.risk_score}
                      risk_category={responseData.risk.risk_category}
                    />
                  )}
                  <button
                    onClick={downloadReport}
                    className="bg-slate-100 hover:bg-slate-200 border border-slate-300 rounded-xl px-4 py-2 text-sm font-semibold text-slate-700 transition-colors"
                  >
                    📥 Download Report (.docx)
                  </button>
                </div>
              </div>

              {/* Alert Banner */}
              {responseData.alerts && responseData.alerts.length > 0 && (
                <AlertBanner alerts={responseData.alerts} />
              )}
            </div>

            {/* Key Stats Grid */}
            {responseData.response?.key_stats && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {responseData.response.key_stats.water_stress_index && (
                  <div className="bg-gradient-to-br from-blue-500 to-cyan-500 rounded-2xl p-6 text-white shadow-lg">
                    <div className="text-4xl mb-3">💧</div>
                    <h4 className="font-semibold text-blue-100 mb-2 text-sm">Water Stress Index</h4>
                    <p className="text-3xl font-black">{responseData.response.key_stats.water_stress_index}</p>
                  </div>
                )}
                {responseData.response.key_stats.estimated_depletion_rate && (
                  <div className="bg-gradient-to-br from-orange-500 to-red-500 rounded-2xl p-6 text-white shadow-lg">
                    <div className="text-4xl mb-3">📉</div>
                    <h4 className="font-semibold text-orange-100 mb-2 text-sm">Estimated Depletion Rate</h4>
                    <p className="text-3xl font-black">{responseData.response.key_stats.estimated_depletion_rate}</p>
                  </div>
                )}
                {responseData.response.key_stats.contamination_zone_risk && (
                  <div className="bg-gradient-to-br from-red-500 to-pink-500 rounded-2xl p-6 text-white shadow-lg">
                    <div className="text-4xl mb-3">⚠️</div>
                    <h4 className="font-semibold text-red-100 mb-2 text-sm">Contamination Zone Risk</h4>
                    <p className="text-3xl font-black">{responseData.response.key_stats.contamination_zone_risk}</p>
                  </div>
                )}
                {responseData.response.key_stats.sdg6_gap && (
                  <div className="bg-gradient-to-br from-green-500 to-emerald-500 rounded-2xl p-6 text-white shadow-lg">
                    <div className="text-4xl mb-3">🎯</div>
                    <h4 className="font-semibold text-green-100 mb-2 text-sm">SDG 6 Gap</h4>
                    <p className="text-3xl font-black">{responseData.response.key_stats.sdg6_gap}</p>
                  </div>
                )}
              </div>
            )}

            {/* Policy Recommendations */}
            {responseData.response?.recommendations && (
              <div className="bg-white rounded-2xl shadow-md p-6">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">
                  📋 Policy Recommendations
                </h3>
                
                <div className="space-y-6">
                  {responseData.response.recommendations.immediate && (
                    <div className="border-l-4 border-purple-500 pl-5">
                      <h4 className="font-bold text-purple-900 mb-3 text-sm">🚨 Immediate Actions</h4>
                      <ol className="space-y-2">
                        {responseData.response.recommendations.immediate.map((action, i) => (
                          <li key={i} className="flex items-start gap-3 text-slate-700 text-sm">
                            <span className="bg-purple-100 text-purple-700 font-bold rounded-full w-6 h-6 flex items-center justify-center text-xs flex-shrink-0 mt-0.5">
                              {i + 1}
                            </span>
                            <span>
                              {typeof action === 'string' ? action : (
                                action.intervention || JSON.stringify(action)
                              )}
                            </span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  )}
                  
                  {responseData.response.recommendations.long_term && (
                    <div className="border-l-4 border-slate-400 pl-5">
                      <h4 className="font-bold text-slate-900 mb-3 text-sm">📅 Long Term Strategy</h4>
                      <ol className="space-y-2">
                        {responseData.response.recommendations.long_term.map((strategy, i) => (
                          <li key={i} className="flex items-start gap-3 text-slate-700 text-sm">
                            <span className="bg-slate-100 text-slate-700 font-bold rounded-full w-6 h-6 flex items-center justify-center text-xs flex-shrink-0 mt-0.5">
                              {i + 1}
                            </span>
                            <span>
                              {typeof strategy === 'string' ? strategy : (
                                strategy.intervention || JSON.stringify(strategy)
                              )}
                            </span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* AI Insights Highlights */}
            {responseData.response?.ai_insights && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {responseData.response.ai_insights.aquifer_recovery_projection && (
                  <div className="bg-blue-50 rounded-2xl p-6 border border-blue-200">
                    <h4 className="font-bold text-blue-900 mb-3 text-sm">🌊 Aquifer Recovery</h4>
                    <p className="text-slate-700 text-sm leading-relaxed">
                      {responseData.response.ai_insights.aquifer_recovery_projection}
                    </p>
                  </div>
                )}
                {responseData.response.ai_insights.economic_impact && (
                  <div className="bg-green-50 rounded-2xl p-6 border border-green-200">
                    <h4 className="font-bold text-green-900 mb-3 text-sm">💹 Economic Impact</h4>
                    <p className="text-slate-700 text-sm leading-relaxed">
                      {responseData.response.ai_insights.economic_impact}
                    </p>
                  </div>
                )}
                {responseData.response.ai_insights.sdg6_alignment && (
                  <div className="bg-purple-50 rounded-2xl p-6 border border-purple-200">
                    <h4 className="font-bold text-purple-900 mb-3 text-sm">🎯 SDG 6 Alignment</h4>
                    <p className="text-slate-700 text-sm leading-relaxed">
                      {responseData.response.ai_insights.sdg6_alignment}
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* Risk Mitigation */}
            {responseData.response?.risk_mitigation && (
              <div className="bg-white rounded-2xl shadow-md p-6">
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">
                  ⚠️ Risk Mitigation
                </h3>
                <div className="space-y-4">
                  {responseData.response.risk_mitigation.small_farmers && (
                    <div className="bg-yellow-50 rounded-xl p-4 border border-yellow-200">
                      <h4 className="font-semibold text-yellow-900 mb-2 text-sm">🧑‍🌾 Small Farmers</h4>
                      <p className="text-slate-700 text-sm leading-relaxed">
                        {responseData.response.risk_mitigation.small_farmers}
                      </p>
                    </div>
                  )}
                  {responseData.response.risk_mitigation.supply_chain && (
                    <div className="bg-orange-50 rounded-xl p-4 border border-orange-200">
                      <h4 className="font-semibold text-orange-900 mb-2 text-sm">🚚 Supply Chain</h4>
                      <p className="text-slate-700 text-sm leading-relaxed">
                        {responseData.response.risk_mitigation.supply_chain}
                      </p>
                    </div>
                  )}
                  {responseData.response.risk_mitigation.monitoring_framework && (
                    <div className="bg-blue-50 rounded-xl p-4 border border-blue-200">
                      <h4 className="font-semibold text-blue-900 mb-2 text-sm">📊 Monitoring Framework</h4>
                      <p className="text-slate-700 text-sm leading-relaxed">
                        {responseData.response.risk_mitigation.monitoring_framework}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Explainability Panel */}
            <ExplainabilityPanel
              calculations={responseData.response?.key_stats}
              reasoning={responseData.response?.ai_insights?.sdg6_alignment}
              sources={[]}
              tools={[]}
            />

            {/* Reset Button */}
            <button
              onClick={reset}
              className="w-full bg-white hover:bg-slate-50 border-2 border-slate-200 rounded-xl px-4 py-3 font-semibold text-slate-700 transition-colors"
            >
              🔄 New Simulation
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
